name: Team 9 CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest 
    container: openjdk 
    steps: 
      - uses: actions/checkout@v2
      - working-directory: ./Projects/P1
      - name: Build Project 
        run: | 
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
