name: Team 9 CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - name: checkout Project
        uses: actions/checkout@v2
      - name: install openjdk
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: compile code and tests
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
      - name: TestPacManValidMoves
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManValidMoves
      - name: TestGhostValidMoves
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostValidMoves
      - name: TestMapMove
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapMove
      - name: TestPacManMove
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManMove
      - name: TestGhostMove
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostMove
      - name: TestMapGetLoc
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapGetLoc
      - name: TestGhostInRange
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostInRange
      - name: TestMapEatCookie
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapEatCookie
      - name: TestPacManInRange
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManInRange
      - name: TestAttack
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestAttack
      - name: TestConsume
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestConsume
      - name: TestMapAttack
        working-directory: ./Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapAttack

