name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest 
    container: openjdk 
    steps: 
      - uses: actions/checkout@v2
      - working-directory: ./Projects/P1
      - name: Build Project 
        run: | 
          javac *.java
